### ISSUE TITLE
Error Message in 'Gated Axis' action by using Set button to reduce the gates

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#162] opened 2024-11-01 11:57 UTC
Hello,
I get an error message when I want to reduce several gates after adding them with the set button and also press the set button. 

![grafik](https://github.com/user-attachments/assets/9d00efd1-58c4-4f48-9d2d-51a886e36ab7)

I also get an error when I press the red ADD button.

![grafik](https://github.com/user-attachments/assets/c2f95d8d-90be-40af-8453-3b54bf5a248b)

**Comment by SyFiD** [comment] 2024-11-01 12:01
Sorry if I'm bombarding you with so many error messages right now. 
I'm in a reporting mood at the moment. 
Please let me know if it gets too much ;-)

**Comment by muchimi** [comment] 2024-11-01 18:00
Thanks for reporting.  I appreciate these reports because GremlinEx is quite complex and has many moving parts and features, and unique use-cases are difficult to regress test.

One reason is automated testing is something I would every much like to have, and also something not currently in the cards especially on the "free" or open source spectrum in the Python ecosystem. Not blaming tools here, it's really the matter of time commitment for me on this hobby and free tool.  In spite of appearances to the contrary, I do test, and it's indeed a challenge of verifying every nook and crany button functions as intended all the time. 

This said, if an issue is reported, I'll do my best to fix it unless I find it first and the community here has been very supportive.

This is fixed in 16m7.

**Comment by muchimi** [comment] 2024-11-01 19:39
Resolved in 
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m8.zip

**Comment by SyFiD** [comment] 2024-11-01 21:44
I'll try it out right away.
Thanks again for your really quick response and good work. Great attitude!

**Comment by SyFiD** [comment] 2024-11-01 22:23
Now it works.
Thanks!

**Comment by SyFiD** [comment] 2024-11-01 22:47
> Thanks for reporting. I appreciate these reports because GremlinEx is quite complex and has many moving parts and features, and unique use-cases are difficult to regress test.
> 
> One reason is automated testing is something I would every much like to have, and also something not currently in the cards especially on the "free" or open source spectrum in the Python ecosystem. Not blaming tools here, it's really the matter of time commitment for me on this hobby and free tool. In spite of appearances to the contrary, I do test, and it's indeed a challenge of verifying every nook and crany button functions as intended all the time.
> 
> This said, if an issue is reported, I'll do my best to fix it unless I find it first and the community here has been very supportive.
> 
> This is fixed in 16m7.

I can well imagine how difficult it is to eradicate errors, especially if you can't replicate them yourself. But so far it works quite well. 
Once again a big compliment for your great work!
I'll do my best to find even more errors ;-)

**Comment by muchimi** [comment] 2024-11-02 14:13
m9 resolves the setGateCount error (I missed the second screenshot).  Should be posted later today.

**Comment by muchimi** [comment] 2024-11-02 19:18
Manual gate count setup fixed in 
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m9.zip

**Comment by SyFiD** [comment] 2024-11-02 22:19
Thank you, now it works as desired.
However, I was able to provoke a few errors when assigning the individual gates. 
I'll test it further tomorrow and then report back.

**Comment by SyFiD** [comment] 2024-11-03 18:57
I tried to provoke some errors today, but I came across the following error:
If I accidentally click on the 'Gates Axis' action twice 
![Screenshot 11_1](https://github.com/user-attachments/assets/64b6b599-c291-47b3-a504-ca8dcf68bbbe)

and close one of them again, this error occurs and I cannot add any further actions for this axis afterwards.
![Screenshot 11_2](https://github.com/user-attachments/assets/587eb043-a7a8-411e-ad44-5cddd938199c)

JG must then be closed so that it can be reworked.

**Comment by SyFiD** [comment] 2024-11-03 19:07
However, the error does not appear if the 2nd Gate Axis is added to the window using the Add button. 
But who wants 2 gate axes ;-)

![Screenshot 11_3](https://github.com/user-attachments/assets/9e9cd9a1-db1b-4261-a8e9-56a827b28267)

**Comment by SyFiD** [comment] 2024-11-03 19:53
Here is a similar error:
If you insert a 'Gate Axis' action and then open a gate with a double-click to insert another action, but delete it again, the 'Gate Axis' window is emptied. 
You must not insert an action again here, otherwise you will get the same error message as in the screenshot above.
It is imperative that you close the 'Gate Axis' window completely, otherwise JG will have to restart.

![Screenshot 11_4](https://github.com/user-attachments/assets/0bd72672-c276-42fb-9070-563a80222fbb)
![Screenshot 11_5](https://github.com/user-attachments/assets/22471e22-d7e1-45d2-8c55-5c253cae220b)
![Screenshot 11_6](https://github.com/user-attachments/assets/f105d28e-ab80-4c84-a190-4c68230ed26d)

**Comment by SyFiD** [comment] 2024-11-03 20:15
If you ignore the error and continue, i.e. switch to another axis and back, a new error message appears.
![Screenshot 11_9](https://github.com/user-attachments/assets/255856ee-71dd-437d-838b-873ef4441e99)

**Comment by muchimi** [comment] 2024-11-04 03:06
I will look at this in the coming days.  Thanks for reporting.

**Comment by muchimi** [comment] 2024-11-04 15:07
The first update on the topic is it will not longer be possible to add actions that are designed to occur only once per input, like the gated axis.  You correctly point out that there is no need for two gated axis inputs, let alone a nested one.
This feature has been added in that if you attempt to add more than one gated axis, or add a gate axis to a gated axis, GremlinEx will now present a message box instead of adding the duplicate or nested action (for the actions marked as singleton.
API wise there is a new flag that is set by the plugin to tell GremlinEx if it's single use per input, or multiple use (default).

The gated axis is also not "wired" to support multiple instances per input which is why it has errors when you use multiple instances, or sub-instances, on the same input, because each instance clobbers the other due to shared data values.

This update will be up in today's patch.

**Comment by muchimi** [comment] 2024-11-04 18:19
The second update is the removal of an action from a gate or range when using an unsaved (new) profile will no longer also remove the visuals on the primary gate axis action.
This update will be in 16 m11.

**Comment by muchimi** [comment] 2024-11-04 18:20
Sorry, 16 m12

**Comment by muchimi** [comment] 2024-11-04 20:22
The update was pushed.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m12.zip

**Comment by SyFiD** [comment] 2024-11-04 23:04
This error seems to be fixed so far, but I could provoke similar ones again.

This one occurred after I inserted a description in the 'Gated Axis' action, deleted it again and moved the axis.
When the error occurs, I have to click away many identical error messages.
![Screenshot 12_3](https://github.com/user-attachments/assets/701dd85c-b534-4e3c-bc39-21dbc4388c2e)

And this one after I added only a 'Merge Axis' action to an axis.
![Screenshot 12_6](https://github.com/user-attachments/assets/77bcbef7-2c0f-4cf0-b9e7-6c7837832e3c)

Here are similar error messages that continue to query the axes after deleting an action and moving the axis.
![Screenshot 12_4](https://github.com/user-attachments/assets/fd582e94-decc-450b-abd7-67e723eb6cf3)
![Screenshot 12_5](https://github.com/user-attachments/assets/b69e285b-227c-476d-8779-7c8fe6513ba5)

These errors seem to occur when programmed and deleted axis actions continue to query the status, don't they? The errors do not occur with the buttons or switches. 

I hope that's not getting too much for you. 
Should I take a break?

**Comment by muchimi** [comment] 2024-11-04 23:44
No breaks for the wary - this is good stuff.   Thanks for reporting.

**Comment by muchimi** [comment] 2024-11-05 03:19
Resolved the deleted action not terminating the hooks into joystick movement updates, causing null or C++ errors.

I have a favor: can you report different issues as tickets for tracking purposes?  It will make it easier for me to track issues and fixes.  Thank you!

On the merged axis action, I'm not able to reproduce the issue if you could elaborate on the steps to reproduce on a different issue, thank you !

**Comment by SyFiD** [comment] 2024-11-05 14:56
Ok, I will make separate reports in the future. 
The last few reports were probably a bit much. But I also didn't know how these errors were connected, so I reported them all here.

**Comment by SyFiD** [comment] 2024-11-05 15:07
I have now opened a new report for the 'Merge Axis' error.

**Comment by muchimi** [comment] 2024-11-05 20:10
> Ok, I will make separate reports in the future. The last few reports were probably a bit much. But I also didn't know how these errors were connected, so I reported them all here.

Thank you.  The difficulty here is some issues are indeed related, and some are not, so having them as separate issues is more helpful in general, even if they are related.

**Comment by muchimi** [comment] 2024-11-05 20:29
Please verify this is functioning correctly on your system now.  Thanks!
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m13.zip

**Comment by SyFiD** [comment] 2024-11-05 22:16
It works so far, but when I now do the test in 'Gated Axis' with inserting and deleting a description in one of the gates, the axis freezes and I get this error message when I try to insert an action again.

![Screenshot 12_7](https://github.com/user-attachments/assets/d5ac651e-7f6f-4e56-b941-f66ef88aea6c)

In addition, the buttons 'Add', 'Set', 'Normalize' and 'Normalize reset' react with their own error messages.

![Screenshot 12_8](https://github.com/user-attachments/assets/261cb0b5-fb4c-4cc6-bb30-2a93e9537e7c)
![Screenshot 12_9](https://github.com/user-attachments/assets/11918324-9e49-4cb7-b2cc-f2a0157ec42c)
![Screenshot 12_10](https://github.com/user-attachments/assets/b0177e92-1549-4376-bc69-38094ab576fb)
![Screenshot 12_11](https://github.com/user-attachments/assets/9d988286-a42f-4e48-8b12-ca5e1c05e6cb)

However, I can now correct the error by deleting the complete 'Gated Axis' action. Then the axis can be moved again and the axis can be assigned again.

**Comment by muchimi** [comment] 2024-11-06 01:42
Thanks. Can you elaborate on "inserting and deleting a description" in a gate?

**Comment by muchimi** [comment] 2024-11-06 13:22
If what you mean is the description action, I am unable to duplicate the issue by trying various permutations of adding/removing it from a gate or range, so it's likely I'm missing a step somewhere to recreate.  Can you give me a step by step?

The normalize buttons both also work for me, but I suspect the two issues may be related as it's the same type of error.

Thanks for the help on this one.

**Comment by SyFiD** [comment] 2024-11-06 16:48
I have now posted a video about the problem.
This shows how I move the 'Dial' axis permanently and insert a 'Gated Axis' action. I then add a description to the gated axis and delete it again immediately.
After that, the axis in the 'Gated Axis' no longer moves, but continues to move at the bottom left of the 'Dial' axis.
The buttons 'Set', 'Normalize' etc. then no longer work either. 
After the complete deletion, all axes work again.

https://github.com/user-attachments/assets/d0d09d14-6b46-49f8-b444-210795d55d6f

**Comment by muchimi** [comment] 2024-11-06 19:57
Perfect thank you!   Vielen Dank.

**Comment by muchimi** [comment] 2024-11-07 02:00
Issue in video resolved in 16 m14
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m14.zip

**Comment by SyFiD** [comment] 2024-11-07 16:36
Now it works. 
Many thanks!

**Closed** 2024-11-07 20:01 UTC
Labels: bug, resolved / verification needed
