### ISSUE TITLE
Mapping function F5 key activates profile

### ISSUE THREAD

**Issue by Smuli34** [muchimi/JoystickGremlinEx#140] opened 2024-10-13 17:38 UTC
Pressing F5 while mapping the button activates the current profile. Happens with "Map to Keybard Ex" with listen mode on. F5 is possible to map via "Select keys".

Pressing F5 seems to activate the profile also from the main app window.

**Comment by muchimi** [comment] 2024-10-13 21:17
That is intended behavior.
What is not is for F5 to trigger the profile when listening to keyboard input...  I'll add an exclusion on the legacy keyboard mapper.

**Comment by muchimi** [comment] 2024-10-16 03:38
This should be resolved in non debug mode in hotfix 5 (I tested and verified with the legacy keyboard mapper listen mode):
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m4_5.zip

**Comment by muchimi** [comment] 2024-10-16 17:30
Closing the issue - we can re-open based on further feedback on this topic if hotfix 5 did not correct the issue.

**Closed by muchimi** 2024-10-16 17:30 UTC
