### ISSUE TITLE
JG 13.40.16ex (m3) - Error by clicking RESPONSE CURVE or RESPONSE CURVE EX action results in an Uncaugth Exception

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#156] opened 2024-10-28 20:35 UTC
Hello,
I have problems with Joystick Gremlin from time to time, but this one drives me to despair and I hope you can find a solution.

1) I get the following error messages when I press the ADD button in the RESPONSE CURVE or RESPONSE CURVE EX action. 

![Screenshot 01](https://github.com/user-attachments/assets/b74879f0-42b1-4971-b7f4-684e8b34fd92)
![Screenshot 02](https://github.com/user-attachments/assets/d0fdebdb-23bc-42b9-8b0e-9006509ad3c6)

2) After I have clicked away the same error message several times, the RESPONSE CURVE appears.

![Screenshot 04](https://github.com/user-attachments/assets/6755ae6f-7a0d-4d76-9376-3b5905d75932)

3) However, as soon as I want to edit the curve by clicking in the curve, I get the same error message.
Which I then have to click away 4 times before it disappears.

![Screenshot 05 (4x)](https://github.com/user-attachments/assets/d544a418-51fb-4cd5-99b0-c96c1d358fa8)

4) I get a similar error message when I try to insert the old RESPONSE CURVE function.

![Screenshot 06](https://github.com/user-attachments/assets/a1a72286-6a6d-4594-ac5a-5a681413b999)

Thank you for this great tool!
I use it often for various sims, and also StarCitizen. 
Thanks in advance for your support.

[system.log](https://github.com/user-attachments/files/17548550/system.log)

**Comment by SyFiD** [comment] 2024-10-29 17:28
Thank you for the speedy processing of the error.
nfortunately, a new error appears when I try to add RESPONSE CURVE EX.

[system.log](https://github.com/user-attachments/files/17560819/system.log)
![Screenshot 07](https://github.com/user-attachments/assets/89f8a124-1914-400d-ae33-05e5b0d10f74)

**Comment by muchimi** [comment] 2024-10-30 03:21
Whoops. I am in the process of troubleshooting the root cause.
It doesn't like the initialization process (the recursive error is a separate issue that's new because of the "fix").
more soon (tm).

**Comment by SyFiD** [comment] 2024-10-30 15:22
No problem, don't stress!
I don't really need this function at the moment. I just want to support you in correcting the errors.

**Comment by muchimi** [comment] 2024-10-31 03:48
I was not able to duplicate the error through testing on my systems however I have hardened the code and ensured default values are present on initialization rather than expecting a curve to be there.  Could be a timing issue.
If this doesn't resolve the issue, we'll take another look.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m6.zip

**Comment by SyFiD** [comment] 2024-10-31 18:18
And finally, a strange reaction. As soon as I click on one of the black arrows to select the first or last point of the curve, the Y value is also set to 0. The curve is then smoothed.
![Screenshot 09](https://github.com/user-attachments/assets/e505f802-86bf-48de-8763-9dab3d19b555)

**Comment by muchimi** [comment] 2024-10-31 21:25
I hopefully squashed this in m7.  Here's a video showing the behavior in m7.

https://github.com/user-attachments/assets/ac3f7f84-f55a-4682-a93a-37858457b552

**Comment by SyFiD** [comment] 2024-11-01 10:01
It works perfectly now!
But there is still a small, relatively insignificant error.
Now you cannot delete the individual items via the trash icon. But it still works via the DELETE button on the keyboard.
Then it would be perfect.
Thank you very much!

![grafik](https://github.com/user-attachments/assets/14ffb368-24f9-4923-8aaa-f521b6fab785)

**Comment by SyFiD** [comment] 2024-11-01 10:06
Thank you very much! Now it works perfectly!

**Comment by SyFiD** [comment] 2024-11-01 10:12
I have now discovered a mistake.
When I press the CENTER button, I get this error message.

![grafik](https://github.com/user-attachments/assets/c6264c70-c8ba-44f6-9cd8-162ba5e0a5dc)

**Comment by SyFiD** [comment] 2024-11-01 11:03
It seems that the END buttons have no effect for me. It does not change the curve behavior.

![grafik](https://github.com/user-attachments/assets/97bba471-7c4c-497a-b0d3-7f675bcda680)

I now get this error message when activating and deactivating the profile.

![grafik](https://github.com/user-attachments/assets/930180a5-1e74-4f75-8ebe-a91e6c8c55ba)

**Comment by muchimi** [comment] 2024-11-01 18:04
> It seems that the END buttons have no effect for me. It does not change the curve behavior. Not even when I use the sliders.
> 
> ![grafik](https://private-user-images.githubusercontent.com/186627409/382262071-97bba471-7c4c-497a-b0d3-7f675bcda680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODQ0NDYsIm5iZiI6MTczMDQ4NDE0NiwicGF0aCI6Ii8xODY2Mjc0MDkvMzgyMjYyMDcxLTk3YmJhNDcxLTdjNGMtNDk3YS1iMGQzLTdmNjc1YmNkYTY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxODAyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjBlZTM4NDNlZTI5OWZhODViYjk1YTRlYmFiYTVjNDJmZTNhNzJjM2Q4NmNkYzkzNjM5YTg0YTNlNDQwOGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nXykZ_eO3KmlyKImEfUwgc2I19y3l2REi-OKOjux_0s)
> 

Deadzone will only change the response when the input is in the range.  The buttons are changing the sliders at the bottom and the deadline values.  Deadzones will not change the curve visually, but will cause the input to be ignored while the input is in that range.

**Comment by muchimi** [comment] 2024-11-01 18:11
> I now get this error message when activating and deactivating the profile. Here when activating:
> 
> ![grafik](https://private-user-images.githubusercontent.com/186627409/382262792-930180a5-1e74-4f75-8ebe-a91e6c8c55ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODQ0NDYsIm5iZiI6MTczMDQ4NDE0NiwicGF0aCI6Ii8xODY2Mjc0MDkvMzgyMjYyNzkyLTkzMDE4MGE1LTFlNzQtNGY3NS04ZWJlLWE5MWU2YzhjNTViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxODAyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTUwNGMxNzM5YzVhMGQ3ZWE3NzlmYjY2ZWUyNWVkYzQwZmRiZjljZWZhZWM2ZmExMDg0ZDI5Y2RmYTJiNjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TKmukY8fsPchdxGYE1KIim6UG09X-4T97xD6ATbf-Zc)
> 
> Here when deactivating:
> 
> ![grafik](https://private-user-images.githubusercontent.com/186627409/382263686-703da7ff-3898-4543-be12-a049192b6caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODQ0NDYsIm5iZiI6MTczMDQ4NDE0NiwicGF0aCI6Ii8xODY2Mjc0MDkvMzgyMjYzNjg2LTcwM2RhN2ZmLTM4OTgtNDU0My1iZTEyLWEwNDkxOTJiNmNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxODAyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2I3OGVmZjVlZmI4NDJjZDZjNDUyNjI5MTMwZDQ2NzA4YTYxNGRlNWFmMjliNzgzOTg2ZWU3N2FjNTEwYjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JIQKbbUIPXea-hMtNXUuWBao7q8RsNG0AV83ubGQUCM)

Resolved in 16m8

**Comment by SyFiD** [comment] 2024-11-01 22:56
> Now I have discovered another error. When I press the CENTER button, I get this error message.
> 
> ![grafik](https://private-user-images.githubusercontent.com/186627409/382252175-c6264c70-c8ba-44f6-9cd8-162ba5e0a5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDE2NjksIm5iZiI6MTczMDUwMTM2OSwicGF0aCI6Ii8xODY2Mjc0MDkvMzgyMjUyMTc1LWM2MjY0YzcwLWM4YmEtNDRmNi05Y2Q4LTE2MmJhNWUwYTVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQyMjQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWNhNzMyNzYxNTczYzUxNDM5NWM4ODc1MTBiYzJkMjQ4MTg4Njk0OWY2Y2VhZGNkZWI4Y2U1N2IwOWNhNDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KtR3NIaiibqr2o48g3m7wEJ-PawN38AxvbDuXXHNbxc)

The center buttons still generate the 'Uncaught exception' error message.
But the other errors have now been corrected.

**Comment by muchimi** [comment] 2024-11-02 19:22
Hi - sorry - I'm unable to pull up your screenshots.  I am not having issues with the center buttons so perhaps a quick video may help?

**Comment by SyFiD** [comment] 2024-11-03 17:52
Hi,
Strangely enough, I had already sent a video yesterday, but somehow all my posts on Github just disappeared.
So here is the video of the error message again.

https://github.com/user-attachments/assets/8596d9ca-9308-418f-b631-055cd41cab57

**Comment by muchimi** [comment] 2024-11-03 19:10
See if m10 works better for you.

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m10.zip

**Comment by SyFiD** [comment] 2024-11-03 21:08
Thanks! 
It works now.

**Closed** 2024-11-04 18:21 UTC
Labels: resolved / verification needed
