### ISSUE TITLE
JG 13.40.15ex (m2.6) - Highlight currently triggered axis and button not highlighting

### ISSUE THREAD

**Issue by Smuli34** [muchimi/JoystickGremlinEx#135] opened 2024-10-09 17:21 UTC
As title says, highlight not working at the moment.
Options checked twice.

**Comment by muchimi** [comment] 2024-10-09 17:32
Thanks for reporting, looking into this.
A screenshot of your selected options would be helpful for me to see if it's a combination thing and for me to duplicate your exact settings. Thanks!

**Comment by Smuli34** [comment] 2024-10-09 17:36
![image](https://github.com/user-attachments/assets/29a43c2a-8c54-48b9-9343-30b4efdd7602)

**Comment by muchimi** [comment] 2024-10-09 17:36
I just tested on the latest pre-release with these options selected and it is functional for me.
I may need to clarify what each option does a bit better:

![image](https://github.com/user-attachments/assets/bb6894c4-b96e-4d8d-bae8-b8a33004a127)

Can you enable the two missing boxes and see what happens?

**Comment by Lolo401** [comment] 2024-10-09 17:39
Tested and functional on my end.

**Comment by muchimi** [comment] 2024-10-09 17:48
I think the checkbox explanation as to what these four options do isn't as clear as it could be.
I shall ponder this.

**Comment by Smuli34** [comment] 2024-10-09 17:49
Not fully functional here. I tested with your setting and it is very random when pressing a button. The small red dot activates but only sometimes highlight....

And while writing this something flashed in UI and highlight works again. 
Sorry for confusion, now it seems to be OK again.

**Comment by muchimi** [comment] 2024-10-10 01:45
Behavior was slightly modified in hotfix 7.

The options dialog is reworked slightly to clarify what each item does.
The tooltips on each now provide what each does and how to use it.

Provided the master highlight mode is enabled, the control keys temporarily enable the axis highlight even if the option is kept off in the dialog, and the shift keys can do the same for buttons.  That logic was changed a bit because it wasn't clear the shift and control keys can temporarily do this.

Here's my current preferred setup:  if I want the axes to highlight, I have to hold a control key down.

![image](https://github.com/user-attachments/assets/653009bd-5d87-4b0d-acaa-1bbad5a169e3)

**Comment by muchimi** [comment] 2024-10-12 21:02
I was able to reproduce when the option is set immediately (works on restart).  Fix inbound in m4.2.

**Comment by muchimi** [comment] 2024-10-13 02:17
Please advise if m4.2 (or above) resolves the issue.
There is a new option to determine if the hotkeys for listening to buttons (shift) or axes (ctrl) also allow the autoswitch to occur.
![image](https://github.com/user-attachments/assets/1e9cf8b1-77de-4971-8635-266357c65c2e)

**Comment by Smuli34** [comment] 2024-10-19 13:41
@muchimi I did a small recording how the highlight works with a tree-stage switch. Attached is also verbose log file. Most of the times highlight now works in 15ex (m4.9). Unfortunately there are still some glitches.

https://github.com/user-attachments/assets/7e4fdc32-e129-46fe-aa0d-484cc21a9c11

[dill_debug.txt](https://github.com/user-attachments/files/17445435/dill_debug.txt)

**Comment by muchimi** [comment] 2024-10-22 17:18
Closing for now unless this occurs again.
The highlight behavior was changed a bit in 13.40.15ex

**Closed by muchimi** 2024-10-22 17:18 UTC
Labels: resolved / verification needed
