### ISSUE TITLE
Question: Sort game controllers in Windows settings

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#167] opened 2024-11-08 11:47 UTC
Question:
Is there a way to sort the game controllers in Windows in JG Ex?
Would this be possible in JG Ex?
I've already tried a few things, but haven't found anything that can reliably change the order in the Windows game controller.

**Comment by muchimi** [comment] 2024-11-08 13:52
Good question - I'll share my understanding: Windows does not provide a way for the user to configure (and retain) a specific device order.  This has been something asked for decades and Microsoft has never, to my knowledge, considered this or implemented it.  It's relatively easy to provide a sorted list as each device has a unique ID and/or hardware identifier (and the sort feature in GremlinEx is exactly that) so I can only think it's a legacy piece in Windows that hasn't changed - we still have the joy.cpl applet in windows that goes back to I think Windows 3.11 so it's been a while.

Devices are usually listed in the order in which they are detected by the operating system.  The detection order varies based on driver and how it's connected.  The last device plugged in is usually the last device in the list, however that is only true until a reset and then the order changes.  The order typically doesn't change once the machine has been reset a few times and you don't constantly plug/unplug devices.  It's why I don't recommend constantly adding/removing devices because we know it's an older part of Windows and tends to cause havoc with sequencing. 

There is one more or less reliable ordering system - vjoy:  the virtual driver lists the devices it creates in sequence so those in my experience provide a reliable sequence that survives a reboot because it is detected and enumerated the same way each time, no matter where they appear in the list, they are usually together.

It's one of the premises of Gremlin and GremlinEx to remove the device ordering problem by accepting whatever it is, and maping it to Vjoy which is more predictable, and then using HID Hide to remove the "mess".

There was a program at one point that used to resequence joysticks in the registry; however, I think that stopped working with windows 10, perhaps even Windows 8 (it's been a while) and it wasn't particularly reliable when I tried it years ago.

My approach for years has been to use vjoy as input to all my sims and games and GremlinEx and its internal sort feature is designed to help.   The device tab re-order does exactly what Windows has failed to do - it's not ideal but I put my most used devices up to the left, and go from there - and GremlinEx does remember that.

**Comment by SyFiD** [comment] 2024-11-08 19:33
Yes, it's a shame that MS no longer has such a sorting function. 
In MSFS2020 it was also poorly implemented at the beginning, but they managed to do it quite well. But I really miss this option for StarCitizen. I'm sure there's a solution, but it's still annoying.
Then I'll probably have to switch all my controller assignment to vJoy again.
And I thought the sorting function in JG was only for the HID tabs with the HID controllers.

**Comment by SyFiD** [comment] 2024-11-08 19:47
Incidentally, I have also had good experiences with HID Hide. It's finally a tool that works for me without any problems. 
Especially in combination with GamePad and a certain sports game, it helped me a lot.

**Comment by muchimi** [comment] 2024-11-08 20:49
I have two VJOY devices used for SC and that seems to work well (the primary reason for two is to have 16 axes).
For MSFS same thing although with four engine aircraft I have a third as well.
I have a barebones Simconnect plugin for MSFS and will enhance that when MSFS 2024 is released to see what I can do with that.  The barebones module works for basic commands and control in MSFS 2020 - the missing piece is custom variables and how to speed up the initial read of all simvars from the sim by parsing the addons folder (that easily takes 2 hours of compute time).

I have not used direct joysticks in a very long time.  The MIDI and OSC pieces, mostly OSC because it's much easier to use, helps using touch surfaces into SC and MSFS and other games quite easily, and lets you use a phone, tablet or separate touch screen computer with GremlinEx.

**Comment by SyFiD** [comment] 2024-11-09 21:24
I haven't done that much work with SimConnect yet. I've only seen that it now supports JG. But it sounds good that you're working on it too. Let's see, maybe that will change for me too ;-)

As I understand it, you can then control MSFS2020 and SC via tablet/mobile phone using a plugin, but what is the difference to e.g. TouchPortal or GameGlass? Or SimDashboard for MSFS2020?
How does it work with the OSC?

**Comment by muchimi** [comment] 2024-11-09 22:26
Let's start with OSC.  OSC is Open Sound Control (or Open Stage Control).  It's a UDP based network protocol to send commands over the network to different devices, typically on port 8000. 
The OSC protocol has largely replaced the older MIDI protocol that was designed for musical instruments and digital instruments. MIDI is very old and very dated, but there are still plenty of controllers that use it.

The more modern ones use OSC to send what can be simplified as text commands with an optional group of parameters, such as, the value of an axis.

OSC today is used to control not just music (digital audio workstations, musical instruments like synthesizers), but also audio and stage equipment, such as lighting, sound  editing workstations, etc...  Media controllers like LoupeDeck and StreamDeck also have OSC plugins.   MIDI is also a very valid protocol because while old, it still has 16 channels, support for up to 127 buttons and 128 values for faders.   What does this have to do with games?

Plenty it turns out because the physical controllers that work with stage systems happen to be full of buttons and faders and knobs, example, Korg Mini, and there is software out there that lets you design using touch screens these control systems.  While originally for music and DJ / live performance control via an Ipad or other touch surface (including Windows), this is like GameGlass on steroids.

I use TouchOSC for this by Hexler for my home cockpit setup and there are also free alternatives out there that do OSC design.

With software like TouchOSC I can easily duplicate GameGlass functionality - with the difference being that it is cheap(er) and custom made, unlimited buttons, axes.   TouchOSC's major flaw right now is that it doesn't do images.  It runs however on any phone and tablet, and on Windows which is terrific for touch screen support and input into games.

**Comment by muchimi** [comment] 2024-11-09 22:31
SImconnect is an API Microsoft provides to interface, read and write data/commands to Flight Simulator.
The simconnect plugin lets you map inputs via GremlinEx to the simulator, such as flight controls and other commands like landing gear, lights, flaps, brakes, pumps, etc...

A number of add-ons in MSFS have custom variables they define and this is where the Simconnect plugin in GremlinEx needs a bit more work, but all planes built-in the simulator can be controlled via GremlinEx today.

Custom variables can be edited manually (I haven't written the docs for that yet) as I'm waiting for MSFS 2024 and the new SDK to see if that can help the cause (I doubt it will).  This is mostly UI work as the base functionality is already there and GremlinEx can easily duplicate the functionality of SpadNext and AxisAndOhs for example today - except the UI needs a bit more work as it is very barebones.

The initial scan for custom variables from the add-on folder can take hours because GremlinEx will literally scan every configuration file to find the relevant definitions based on the SDK configuration data.   If you have lots of add-ons, like I do, it takes hours because it has to process thousands of files.

Not ideal and I'm working on a better solution.

**Comment by SyFiD** [comment] 2024-11-10 22:12
The OSC function makes me really curious.
I have GameGlass, SimDashboard and Touchportal on my computer, but I'm still not completely satisfied with the possibilities they offer.
But maybe OpenStageControl is something for me.
I would like to design something myself. 
Unfortunately, I have hardly any programming skills. Are there any OSC profiles on the internet that you could possibly use as a basis for your own profiles for MSFS2020 or SC?

Do you also use AxisAndOhs or SpadNext yourself or do you do it all with GremlinEx now?

**Comment by muchimi** [comment] 2024-11-10 23:18
I am moving away from AxisAndOhs to GremlinEx although that migration will finish when I have MSFS 2024 and the new SDK.
The basics function now.

All the game glass stuff I do either via Stream Deck or TouchOSC. 

What I recommend you do, if you want to test things out and you have a touch screen at your disposal (it has to be on a machine other than your gaming machine) - is to download a copy of TouchOSC and try it out.

There is also freeware for OSC - not sure how good it is.   I like TouchOSC because it has scripting if needed, although frankly, I'm doing most of what I need to do right now with Stream Deck.   I probably will map the new power stuff to TouchOSC when I am not fixing bugs in GremlinEx or testing bugs in SC lol.

**Comment by muchimi** [comment] 2024-11-10 23:18
I also have some examples provided on how to use TouchOSC in the docs.

**Comment by muchimi** [comment] 2024-11-12 21:55
Closing discussion for now.

**Closed by muchimi** 2024-11-12 21:55 UTC
Labels: question
