### ISSUE TITLE
JG 13.40.16ex (m33) - Changing mode results in a ResponseCurveEx error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#209] opened 2024-11-26 02:00 UTC

**Comment by Lolo401** [comment] 2024-11-26 02:03
The following was observed in m33.  Switching between modes with an active profile containing Response Curves Ex resulted in the following at the mode change:
![image](https://github.com/user-attachments/assets/1a6fbf6b-18d0-48ed-ab58-dc2bb8c11584)

Note: This was confirmed on m30 as well.  However, working fine in m17.

Profile used for testing hereby attached.  The error occured when using button 58 on the VPC Throttle to go from the GND VEHICLE mode to COMMOM mode.

[Updated_File - .xml.txt](https://github.com/user-attachments/files/17911595/Updated_File.-.xml.txt)

**Comment by muchimi** [comment] 2024-11-26 23:53
Resolved in m37.

**Comment by muchimi** [comment] 2024-11-27 14:01
Please validate the issue is resolved, thanks.

**Comment by Lolo401** [comment] 2024-11-27 18:51
Appears to be fixed in m37.

**Closed** 2024-12-11 18:49 UTC
Labels: resolved / verification needed
