### ISSUE TITLE
Slight Axel drift with Vjoy + Joystick Gremlin Ex

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#217] opened 2024-11-29 11:08 UTC
I am experiencing an issue with the JGEx: 
All the axes are slightly drifting. I don't know if this is a problem with Vjoy or the JGEx itself. 
The normal axis is calibrated and functioning well, but the drifting occurs only when I use Vjoy in conjunction with the JGEx.

I tried using "Vjoy 2.2.2" to see if it solved the issue, but JGEx is not working with "Vjoy 2.2.2" (only 2.1.9 is working right now with JGEx). The JGEx recognizes the virtual device, but there is no output when activating JGEx.

![image](https://github.com/user-attachments/assets/41d7b5ad-c1d0-48d8-9238-5c523119a367)

![image](https://github.com/user-attachments/assets/bcef0b4c-cef8-44e0-aa2e-c46b176854c8)

**Comment by muchimi** [comment] 2024-12-01 13:10
The drift is interesting as that means there is some cumulative input error on a straight mapping.  JGEX will take whatever input - which by DirectX standards is going to be -32768 to +32767 and convert that to a -1 to +1 value.  If you use calibration, it could mess with that so the first thing I would do is get rid of calibration in JGEX to see if the problem persists (process of elimination) and see what the input is doing.  If the input is not moving, and you are observing a drift, something is causing it and I'm not sure what that could be code wise.

In the input viewer (tool menu) would show you what JGEX is seeing as input - the question is - is that drifting?

**Comment by mnf1980** [comment] 2024-12-01 13:40
The regular Axis (without Vjoy + JGEx) is functioning correctly with no drift. And I didn't use any calibration with JGEx.

The JGEx appears to be outputting fine, as shown in the "input viewer," but the drift is evident in the game and DIview. 

I also tested the legacy JG and observed the same issue. 

I have provided two pictures for the SimAppPro (Joystick WinWing app) and JGEx and found a discrepancy in the output numbers between the two applications. 

Additionally, divination is not on one Axis; drift is with all Axes. Moreover, the game detects the axis range from -100 to -1 and from -1 to 99.

I hope this information helps in finding out the problem.
I also found others have the same problem:
https://www.reddit.com/r/hotas/comments/syzmq2/small_axel_drift_with_vjoy_joystick_gremlin/

![image](https://github.com/user-attachments/assets/801e502a-356f-405d-ab6e-90ac8c80eb75)

![image](https://github.com/user-attachments/assets/75d6f4f7-c1ee-4ff6-b60a-9d0d5f2f5030)

**Comment by muchimi** [comment] 2024-12-03 01:30
I have reworked the curve handling in general in m42 along with a new API ability.  I suspect some drifting may have been caused by curvature applied a few times at least in some edge cases.
I will rework next the calibration bits as I suspect they are not behaving well with the updated "wiring".

**Comment by muchimi** [comment] 2024-12-07 14:58
M43 includes a new data structure to keep track of the execution sequence, which helps with the correct sequencing of successive curve applications (which can cause a drift in some situations).  
M44 introduces a complete rework of the calibration process (this is a gut/replace), one goal was to have a clearer view of what the input is doing and how calibration data impacts the output, and to visualize it "live".  
A drift could be many things - and my goal was to identify with some clarity where the drift could occur.
Please try M44 to review the new calibration system and behavior of the impacted inputs (usage guide updated in the docs in the dev branch).  Thanks!

**Comment by muchimi** [comment] 2024-12-19 19:06
Marking this resolved pending new information.
Most current release at time of closing:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip

**Closed by muchimi** 2024-12-19 19:06 UTC
Labels: resolved / verification needed

**Comment by mnf1980** [comment] 2024-12-30 20:48
I uploaded a video to describe the issue, as is it's still in m53

https://github.com/user-attachments/assets/022c18ae-db73-411f-9046-bbf0ff0f4203
