### ISSUE TITLE
13.40.14ex (m14) - Map to Keyboard (Hold) does not hold the key depressed

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#95] opened 2024-09-01 17:14 UTC
An action was created like this:
![image](https://github.com/user-attachments/assets/addce5b1-9239-48a8-a8b0-5ed4ead23b44)

The expected behavior was that the key would be kept depressed until released by another action.  However, a single key press was observed both in game and when using Notepad.

Workaround: Use a macro with conditions:
![image](https://github.com/user-attachments/assets/f5f60a75-f7a8-4e4b-970c-1fc6b75ed39e)
![image](https://github.com/user-attachments/assets/8d007fba-f547-4408-a355-35521d388ac5)

**Comment by muchimi** [comment] 2024-09-01 21:49
On (1), unable to duplicate.
Perhaps it has to do with what it's attached to.   In my test when I map MapKeyboardEx to a joystick button, the key (or keys) remain pressed while the button is pressed, and released when the button is released.


https://github.com/user-attachments/assets/71f3bf7a-8583-4131-8ef8-d15107c38206

I will be testing the macro (my favorite plugin!)

**Comment by Lolo401** [comment] 2024-09-01 22:37
I see, it was a misunderstanding of the option on my part.  I was under the impression that selecting 'Hold' would keep the key depressed until a release command would get send.
Maybe some room for an additional feature: In games, some interactions require the user to keep a key depressed to access an interaction menu, the menu goes away when the key is released.  Ex: The interaction feature in Star Citizen. Keeping F depressed allows us to interact with the MFD's until F is released.

I was trying to implement a way to use the interaction feature with a thumbstick on my Virpil.  The mouse axis are mapped to the X and Y axis of the thumbstick. I want the interaction mode to be entered by depressing the thumbstick itself (button 13) and keep the interaction alive until Btn 13 is depressed again.  The reason is that keeping the thumbstick depressed is a pain in the ass.

**Comment by Lolo401** [comment] 2024-09-01 22:46
I tried using this method:
![image](https://github.com/user-attachments/assets/4cb1cb63-49a5-4559-b663-e47dc068e6fe)
![image](https://github.com/user-attachments/assets/ed3005e6-ff3c-4c6e-a2d3-6d7543183a8f)

Which should, based on my understanding of Press and Release, work as the macro.  However, it results in only a single F press being sent.

**Comment by muchimi** [comment] 2024-09-02 02:50
The four modes explained in terms of (intended) behavior:
- hold  this mode is temporary while the input is pressed - this is designed for momentary buttons, not so much axes.  All keys in the latch group will be pressed when the input is pressed and while held, and released when the input is released.
- pulse this mode sends a press/release based on pulse duration and is triggered on input press - the keys will be released even if the input is still held and the pulse timer expires.   A minimum of 250ms is recommended for this mode as most game loops are 200ms or more when they check.
- press this mode issues a keydown on all latch key groups - this corresponds to a "make" code.  The keys are never released and will need a manual release at some point. 
- release this mode issues keyup on all latch key groups - this corresponds to a "break" code.  The keys are released regardless of the input.   


Of these two modes, Press and Release should go together as pairs to avoid keyboard problems.

These modes are not intended to be used in conjunction with conditions.

**Comment by muchimi** [comment] 2024-09-02 19:37
Works as intended.
Added autorepeat mode, and mode description to the action.

**Closed by muchimi** 2024-09-02 19:37 UTC
