### ISSUE TITLE
Selecting a mode crashes the software

### ISSUE THREAD

**Issue by alex-smtv** [muchimi/JoystickGremlinEx#8] opened 2023-07-07 04:26 UTC
From a fresh new profile:

- Tools -> Managed Mode
- Add new mode (let's call it Test)
- Select the mode created (Test) at the upper-right side of the window.
- The software hard crashes (no error window)

**Comment by Jawada74** [comment] 2023-07-10 20:54
I can confirm this behavior. Program closes without error message.
Regards

**Comment by ZK-273** [comment] 2023-09-19 21:59
Been watching this and have been interested in this version.  However, since I work with modes a lot, this kind of bug is something that's been holding me back.  Hope there's a fix incoming.  Thanks for all the efforts @muchimi

**Comment by muchimi** [comment] 2023-09-20 16:13
Tracing through the code on mode change, I found that QT crashed when doing a specific UI update.  The simple change turns this update off.  Updated release below to try to see if this fixes the crash on mode change while in the UI and not in run mode.
I did a quick test and no longer experienced the crash.

https://github.com/muchimi/JoystickGremlinEx/releases/tag/10.40.3ex

**Comment by muchimi** [comment] 2023-09-20 17:52
I'm going to close this one for now - we can re-open if the code fix isn't completely addressing the issue with QT.

**Closed by muchimi** 2023-09-20 17:52 UTC
