### ISSUE TITLE
M31: Deleting empty container generate error

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#201] opened 2024-11-23 11:41 UTC
Removing the actions from the container and then deleting the container generates an error.
In the picture below, the first container will delete successfully, but the second container (which has no actions) will generate an error. Adding actions (both) again will allow the deletion of the container.

Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 669, in <lambda>
   File "gremlin\ui\device_tab.py", line 548, in remove_container
 TypeError: 'NoneType' object is not iterable

![image](https://github.com/user-attachments/assets/82bae55c-ee9b-4cf5-8b9b-ddc4216c380b)

**Comment by muchimi** [comment] 2024-11-24 18:39
Resolved in m33.

**Comment by muchimi** [comment] 2024-11-24 20:09
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m33.zip

**Comment by mnf1980** [comment] 2024-11-24 20:58
it is working fine when pressing the x, but it still generates error with (ButtonContainer, DoubleTap, and Temp)

![image](https://github.com/user-attachments/assets/249e47e7-135e-451e-8cb9-f5f629230d4e)

**Comment by muchimi** [comment] 2024-12-30 19:01
I was unable to reproduce this.
The current prerelease is m53:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m53.zip

We can reopen if the issue persists.

**Closed by muchimi** 2024-12-30 19:01 UTC
Labels: researching, resolved / verification needed

**Comment by mnf1980** [comment] 2024-12-30 19:59
I still have the issue not resolved in m53:
More details in the video:

https://github.com/user-attachments/assets/e9f80b8b-2f70-4aa2-98ad-b2e0ddea81cc
