### ISSUE TITLE
Discussion on Input repeater not working on Tempo (and probably other complex usages)

### ISSUE THREAD

**Issue by alex-smtv** [muchimi/JoystickGremlinEx#5] opened 2023-06-29 00:36 UTC
Hello, me again.

So this is a big one and may not be easily fixable, but I wanted to get your opinion about it. The issue I'm going to describe also exists in the original gremlin software. In fact I originally made several research to see if I could find a fix or band-aid solution about it and I stumble on gremlinEx which I wanted to see if it resolved the issue or not: sadly it doesn't but there's still interesting features keeping me around.

So here are the details. As you may know, having a physical device showing at the same time of having mappings to vjoy is going to create confusion for bindings in-game. For that we have the input repeater. The thing is, the implemented input repeater seems to be working on the simple scenario of: one physical button press => one vjoy button. When it gets more complicated it seems the input repeater is getting confused.

In my setup I use the Tempo logic (short press = one vjoy button, long press = another vjoy button), so I'll focus on that part. Simply put, the input repeater doesn't always repeat the appropriate output and it even seems the tempo delay somehow affects the behavior.

Here's two examples. One with 0.50 delay, and another with 0.20 delay. Both examples will use one physical button mapped to a tempo logic on which short press = vjoy btn 1 and long press = vjoy btn 2. 

With 0.50 delay, a short press will result of vjoy btn 1 to repeat (correct). A long press will result of vjoy btn 1 to repeat (not correct, should be btn 2):

https://github.com/muchimi/JoystickGremlinEx/assets/13024466/dbad1d4f-749a-4477-bb49-a932b0a67b8b

With 0.20 delay, a short press will result of vjoy btn 2 to repeat (not correct, should be btn 1). A long press will result of vjoy btn 2 to repeat (correct):

https://github.com/muchimi/JoystickGremlinEx/assets/13024466/f1194995-c995-4f89-a8d5-eca9e82a7205

(VjoyRemap has the same behavior)

So as you can see things are getting real weird. This is an important feature for me to work, but I got the feeling from my understanding it won't be something easy to correct. What is your opinion on it? Did you already notice it?  Do you see a way to make it work (gremlin code or plugins) or is it a though one to tackle? I'm trying to figure out if I can have some hope or if I should put aside the idea on getting the repeater to work on my use case.

Sorry for the wall of text and thanks in advance.

**Comment by Lolo401** [comment] 2024-01-29 17:31
Hi,
I don''t know if you are still monitoring this issue but if so, I found that if you set the short Press as a Pulse Button, it works as intended :
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/a7c830dd-6a7b-43bb-8cf8-e9f8f5feb488)

Cheers

**Comment by muchimi** [comment] 2024-04-14 13:36
Some race conditions in the UI were causing some challenges with data being reset before it could be saved.
This came up with macro and conditions quite a bit.
I'm not sure if the issue is persisting at this point.

**Comment by muchimi** [comment] 2024-04-26 20:42
I'm going to close this one for now, pending more input, as the tempo feature has now been tested with a pair of actions and seems to work as designed, but we can re-open it if issues with tempo crop up again.

**Closed by muchimi** 2024-04-26 20:42 UTC
