### ISSUE TITLE
No Output axis to select from when using VjoyRemap Set Axis Value

### ISSUE THREAD

**Issue by fjdiazt** [muchimi/JoystickGremlinEx#121] opened 2024-09-16 18:34 UTC
v3_40_14_m22

When using VjoyRemap with either Set Axis Value, Set Axis Range or Invert Axis, there is no outputs in the selection list. I would expect the vJoy axis to be listed.

![image](https://github.com/user-attachments/assets/3d075663-ffbc-4838-a1fe-7a4753ed58c3)

**Comment by muchimi** [comment] 2024-10-16 17:50
Bug confirmed.  Will fix this in m4 hotfix 6.

**Comment by muchimi** [comment] 2024-10-16 19:40
Resolved in m4.6.  Turns out it was also impacting some other modes.
![image](https://github.com/user-attachments/assets/23d41db5-1170-4a5b-8295-3c4ee8a32457)

**Comment by muchimi** [comment] 2024-10-16 21:15
Resolved in https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m4_6.zip

**Closed by muchimi** 2024-10-16 21:15 UTC
Labels: researching
