### ISSUE TITLE
13.40.16(m44) Cycle Modes - Text-to-speech

### ISSUE THREAD

**Issue by Rolln-dev** [muchimi/JoystickGremlinEx#228] opened 2024-12-08 00:46 UTC
I use the ${current_mode} variable when switching modes.  It seems like it is now containing the mode `switched from` and not the mode `switched to`.

**Comment by muchimi** [comment] 2024-12-08 15:26
Thanks for reporting.
${current_mode} in TTS points to the current runtime mode at the time it gets executed - which will be (just looking at the code as I write this) whatever mode the TTS action appears in.  So the behavior you describe is correct from the code perspective.

Now if the TTS action appears as part of the new mode selected, and still has the wrong mode, that would be a wiring issue on the code's end, hence why I need clarity on the behavior you'd like to see (hear?).

Are you expecting for TTS to say the new mode before it has switched?  So something like a ${to_mode}?

**Comment by Rolln-dev** [comment] 2024-12-11 01:31
So before having it set up like in the pic, when the mode was switched, it would say the new mode name.  Now it seems to say the mode name that it was switched from.  Doesn't matter to me which way you'd like to address it, `${to_mode}` would be fine.
![image](https://github.com/user-attachments/assets/39e439d4-f2c6-43fe-b5ce-f864eb407e18)

**Comment by muchimi** [comment] 2024-12-11 02:21
I think the way the GremlinEx wiring works this will not work as intended because the TTS will fire off in the wrong mode.
The best option right now until I think of this some more is for you to use the new mode feature where you can attach an action on mode activation.  Right now however this means you'll need to add one entry per mode until I add a pair of global mode inputs that will fire on any mode change.  So until then, you'll need a TTS entry for each mode you've created when they activate and that should give you the correct behavior.

On top of wiring changing to clear up some challenges with the UI (moving to an event based model internally) - TTS is also a different animal because it's now threaded - for performance - so it fires off a process to do the TTS and what would happen is the variable would probably change, on rapid mode changes, because they are quite fast now, to the wrong variable as it reads the data and it's not possible to predict what it will read because it depends on what you say, when the thread runs, and other actions so it not as simple as it perhaps once was.

Once I have the two global mode inputs defined and available, that should resolve your issue permanently with a single TTS entry for all mode changes.

**Comment by muchimi** [comment] 2024-12-11 02:22
The new mode feature and how to use it is in the updated documentation linked in the patch notes.

**Comment by Rolln-dev** [comment] 2024-12-11 03:28
Ok great.  I will take a look at the docs.  This is not a huge deal, don't make it a priority, I'm sure you have other more pressing things to work on.  But thanks!

**Comment by muchimi** [comment] 2024-12-16 22:22
I will mark it partially resolved using the new mode mechanism (which will pull the correct mode when executed).
The transition between modes is still problematic in terms of maintaining states between transitions and the TTS module uses a rather non scientific method for this...
I think one of the to-dos here is to come up with some sort of history tracking which isn't implemented yet but on my future options list.

**Closed by muchimi** 2024-12-16 22:22 UTC
Labels: Additional context/info needed
